package cpuid

const (
	HypervVendorSignature    string = "Microsoft Hv"
	HypervInterfaceSignature string = "Hv#1"
)

func HypervSupportEnabled() bool {
	return HypervVendorIDSignatureString == HypervVendorSignature && HypervInterfaceSignatureString == HypervInterfaceSignature
}

var HypervSupport bool

var HypervCPUIDMax uint32

var HypervVendorIDSignatureString string

var HypervInterfaceSignatureString string

var hypervFeatureFlags uint64

func HypervHasFeature(flag uint64) bool {
	return (hypervFeatureFlags & flag) != 0
}

var HypervFeatureNames = map[uint64]string{
	HYPERV_GUEST_DEBUGGING:                                    "GUEST_DEBUGGING",
	HYPERV_PERFORMANCE_MONITOR:                                "PERFORMANCE_MONITOR",
	HYPERV_PCPU_DYNAMIC_PARTITIONING_EVENTS:                   "PCPU_DYNAMIC_PARTITIONING_EVENTS",
	HYPERV_HYPERCALL_INPUT_PARAMETERS_XMM:                     "HYPERCALL_INPUT_PARAMETERS_XMM",
	HYPERV_VIRTUAL_GUEST_IDLE_STATE:                           "VIRTUAL_GUEST_IDLE_STATE",
	HYPERV_HYPERVISOR_SLEEP_STATE:                             "HYPERVISOR_SLEEP_STATE",
	HYPERV_NUMA_DISTANCE_QUERY:                                "NUMA_DISTANCE_QUERY",
	HYPERV_TIMER_FREQUENCIES_QUERY:                            "TIMER_FREQUENCIES_QUERY",
	HYPERV_SYTHETIC_MCE_INJECTION:                             "SYTHETIC_MCE_INJECTION",
	HYPERV_GUEST_CRASH_MSR:                                    "GUEST_CRASH_MSR",
	HYPERV_DEBUG_MSR:                                          "DEBUG_MSR",
	HYPERV_NPIEP:                                              "NPIEP",
	HYPERV_DISABLE_HYPERVISOR:                                 "DISABLE_HYPERVISOR",
	HYPERV_EXTENDED_GVA_RANGES_FOR_FLUSH_VIRTUAL_ADDRESS_LIST: "EXTENDED_GVA_RANGES_FOR_FLUSH_VIRTUAL_ADDRESS_LIST",
	HYPERV_HYPERCALL_OUTPUT_RETURN_XMM:                        "HYPERCALL_OUTPUT_RETURN_XMM",
	HYPERV_SINT_POLLING_MODE:                                  "SINT_POLLING_MODE",
	HYPERV_HYPERCALL_MSR_LOCK:                                 "HYPERCALL_MSR_LOCK",
	HYPERV_USE_DIRECT_SYNTHETIC_TIMERS:                        "USE_DIRECT_SYNTHETIC_TIMERS",
}

const (
	_ = uint64(1) << iota
	HYPERV_GUEST_DEBUGGING
	HYPERV_PERFORMANCE_MONITOR
	HYPERV_PCPU_DYNAMIC_PARTITIONING_EVENTS
	HYPERV_HYPERCALL_INPUT_PARAMETERS_XMM
	HYPERV_VIRTUAL_GUEST_IDLE_STATE
	HYPERV_HYPERVISOR_SLEEP_STATE
	HYPERV_NUMA_DISTANCE_QUERY
	HYPERV_TIMER_FREQUENCIES_QUERY
	HYPERV_SYTHETIC_MCE_INJECTION
	HYPERV_GUEST_CRASH_MSR
	HYPERV_DEBUG_MSR
	HYPERV_NPIEP
	HYPERV_DISABLE_HYPERVISOR
	HYPERV_EXTENDED_GVA_RANGES_FOR_FLUSH_VIRTUAL_ADDRESS_LIST
	HYPERV_HYPERCALL_OUTPUT_RETURN_XMM
	_
	HYPERV_SINT_POLLING_MODE
	HYPERV_HYPERCALL_MSR_LOCK
	HYPERV_USE_DIRECT_SYNTHETIC_TIMERS
)

var hypervRecommendationFlags uint64
var hypervSpinlockRetries uint64

func HypervGetSpinlockRetries() uint64 {
	return hypervSpinlockRetries
}

func HypervHasAdditionalNestedEnlightenments() bool {
	// see spec
	return (hypervRecommendationFlags & HYPERV_NESTED_EVMCS) != 0
}

func HypervHasRecommendation(flag uint64) bool {
	return (hypervRecommendationFlags & flag) != 0
}

var HypervRecommendationNames = map[uint64]string{
	HYPERV_HYPERCALL_ADDRESS_SPACE_SWITCH:    "HYPERV_HYPERCALL_ADDRESS_SPACE_SWITCH",
	HYPERV_HYPERCALL_LOCAL_TLB_FLUSH:         "HYPERV_HYPERCALL_LOCAL_TLB_FLUSH",
	HYPERV_HYPERCALL_REMOTE_TLB_FLUSH:        "HYPERV_HYPERCALL_REMOTE_TLB_FLUSH",
	HYPERV_MSR_APIC_REGISTERS:                "HYPERV_MSR_APIC_REGISTERS",
	HYPERV_MSR_SYSTEM_RESET:                  "HYPERV_MSR_SYSTEM_RESET",
	HYPERV_RELAXED_TIMING:                    "HYPERV_RELAXED_TIMING",
	HYPERV_DMA_REMAPPING:                     "HYPERV_DMA_REMAPPING",
	HYPERV_INTERRUPT_REMAPPING:               "HYPERV_INTERRUPT_REMAPPING",
	HYPERV_x2APIC_MSR:                        "HYPERV_x2APIC_MSR",
	HYPERV_DEPRECATING_AUTOEOI:               "HYPERV_DEPRECATING_AUTOEOI",
	HYPERV_SYNTHETIC_CLUSTER_IPI:             "HYPERV_SYNTHETIC_CLUSTER_IPI",
	HYPERV_EXPROCESSORMASKS:                  "HYPERV_EXPROCESSORMASKS",
	HYPERV_NESTED:                            "HYPERV_NESTED",
	HYPERV_INT_MBEC_SYSCALLS:                 "HYPERV_INT_MBEC_SYSCALLS",
	HYPERV_NESTED_EVMCS:                      "HYPERV_NESTED_EVMCS",
	HYPERV_SYNCED_TIMELINE:                   "HYPERV_SYNCED_TIMELINE",
	HYPERV_DIRECT_LOCAL_FLUSH_ENTIRE:         "HYPERV_DIRECT_LOCAL_FLUSH_ENTIRE",
	HYPERV_NO_NON_ARCHITECTURAL_CORE_SHARING: "HYPERV_NO_NON_ARCHITECTURAL_CORE_SHARING",
}

const (
	HYPERV_HYPERCALL_ADDRESS_SPACE_SWITCH = uint64(1) << iota
	HYPERV_HYPERCALL_LOCAL_TLB_FLUSH
	HYPERV_HYPERCALL_REMOTE_TLB_FLUSH
	HYPERV_MSR_APIC_REGISTERS
	HYPERV_MSR_SYSTEM_RESET
	HYPERV_RELAXED_TIMING
	HYPERV_DMA_REMAPPING
	HYPERV_INTERRUPT_REMAPPING
	HYPERV_x2APIC_MSR
	HYPERV_DEPRECATING_AUTOEOI
	HYPERV_SYNTHETIC_CLUSTER_IPI
	HYPERV_EXPROCESSORMASKS
	HYPERV_NESTED
	HYPERV_INT_MBEC_SYSCALLS
	HYPERV_NESTED_EVMCS
	HYPERV_SYNCED_TIMELINE
	_
	HYPERV_DIRECT_LOCAL_FLUSH_ENTIRE
	HYPERV_NO_NON_ARCHITECTURAL_CORE_SHARING
)
